version: '3'

services:
  gowitness:
    image: leonjza/gowitness
    container_name: gowitness
    command: gowitness server --address :8080
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - "8080:8080"
    networks:
      - app-network

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - gowitness
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email jack@oxe.dev --agree-tos --no-eff-email --force-renewal -d oxe.dev

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /root/gowitness.io/dhparam/
      o: bind

networks:
  app-network:
    driver: bridge
